### ISSUE TITLE
huge file size

### ISSUE THREAD

**Issue by nicolasvahidzein** [zhanziyang/vue-croppa#13]
Hello, i really love your module but i was wondering if you can explain to me the quality setting.

On 2 processing is quite long and gives a huge file size, above 3 and 4 it calculates for an insane amount of time and produces a file size that is enormous.

When i upload a 53k image i get back a 1 meg image no setting 2 and 8 megs on setting 5.

What am i doing wrong please?

**Comment by zhanziyang** [comment]
What value is `width` and `height` please?

`quality` describes how many times larger the output image will be than the size you see, which is set by `width` and `height`.

if you have
```html
<croppa :width="300" :height="300" :quality="2"></croppa>
```
then the image you get will be 600x600 (300 * 2 x 300 * 2)

**Comment by nicolasvahidzein** [comment]
it was about 600 square.

**Comment by zhanziyang** [comment]
Please try this little experiment: https://jsfiddle.net/zhanziyang/jdcvpvty/5/

My conclusion is, there are 3 ways in which you can compress the file size:

1. Set smaller values to `quality` prop to decrease image visual size. This will decrease the file size but will also make image look smaller. I wonder if I have explained clearly in the last post about what `quality` does. Anyway, this approach is not recommended because usually we don't want to sacrifice image size to get a smaller file size.

2. Compress the file by **giving the second and third arguments to [`generateBlob`](https://github.com/zhanziyang/vue-croppa#mycroppagenerateblob-callback-function-mimetype-string-qualityargument-number-) or [`promisedBlob`](https://github.com/zhanziyang/vue-croppa#mycroppapromisedblob-mimetype-string-qualityargument-number-)**.  I use this method in the jsfiddle example above. Setting the second argument to `'image/jpeg'` works great, setting it to `'image/webp'` works even better. Go try it.

3. Try using croppa together with npm modules like this: https://www.npmjs.com/package/canvas-compress, which receives a blob and compress it.

Sorry I have not yet tried (3), so not sure if it actually works. So far I think (2) is the best approach if you accept jpeg or webp formats. Please tell me if it works or not. Thanks : )

**Comment by nicolasvahidzein** [comment]
Hey buddy, the extra work is a bit much to be honest, but the file size issue in base64 is scary. I will most likely have to look for another alternative. Thank you so much for your kind help, you are a good man. Much appreciated.

**Comment by zhanziyang** [comment]
No problem ; )

**Comment by zhanziyang** [comment]
Wait, if what you want is to compress the base64 data. I want to add that you can try this:
```js
var canvas = myCroppa.getCanvas()
var url = canvas.toDataURL('image/jpeg', 0.5) // 0.5 means half of the default quality
```

**Comment by zhanziyang** [comment]
With version 0.2.0+,
```js
var compressedDataUrl = myCroppa.generateDataUrl('image/jpeg', 0.5)
```
The result is the same as the code post above.
