### ISSUE TITLE
Resizing the container resets zoom and pan

### ISSUE THREAD

**Issue by chrisnetonline** [zhanziyang/vue-croppa#26]
This is reproducible using the demo.

**Comment by zhanziyang** [comment]
Yes, this can be fixed but I think it's only possible when `prevent-white-space` is `false`?
If we don't reset the image to fill the container, It's hard to make `prevent-white-space` work when resizing.

**Comment by chrisnetonline** [comment]
If the component that is controlling the size of vue-croppa can maintain the aspect ratio (changing the height and width at the same time) then we could avoid having whitespace that would trigger prevent-white-space.

**Comment by zhanziyang** [comment]
Not really. Even if croppa's aspect ratio is fixed, as long as its size is changeable, it's very likely that the whitespace will reveal.

<img src="http://i.imgur.com/YmY02CP.png">

And vue-croppa promises to not reveal whitespace if `prevent-white-space` is set to `true`, which is why I said "it's only possible when `prevent-white-space` is `false`".

**Comment by zhanziyang** [comment]
In v0.3.4, if `prevent-white-space` is `false` (which is the default value), resizing container won't cause image reset.
