### ISSUE TITLE
myCroppa.chooseFile() not working with Phonegap on Android phone 

### ISSUE THREAD

**Issue by Peh4** [zhanziyang/vue-croppa#27]
Hello,

I noticed that nothing happen when i tap on the area, or when i click the button
<button @click="myCroppa.chooseFile()">CHOOSE FILE...</button>

https://github.com/zhanziyang/vue-croppa/blob/884ab11aeb4fd3fc21f19e8b1e059f21d816bd4c/src/cropper.vue#L395

I read that the way the input is hidden matters for Android phones
http://jianjye.com/how-to-fix-the-trigger-click-file-upload-input-android-4-2-2-stock-browser-problem/

tested on Samsung S5mini 
Android 6.0.1

**Comment by zhanziyang** [comment]
I modified the code according to the article and published a new version (v0.3.5). 
Could you test it again and tell me if it works now? I can't test it because I don't have the problem on my Android device.

I'm also guessing that it might be the default `accept` value that is not compatible with your device. Try setting it to `accept="image/*"` and see if it works.

**Comment by Peh4** [comment]
I use Phonegap in my project, I think the problem is related to it because your exemple is working well in my phone regular browser, but nothing happened when i test my project with v0.3.5 in the phonegap app
I will ask some help in the Phonegap forum

Thanks

**Comment by Peh4** [comment]
https://issues.apache.org/jira/browse/CB-2627

It's working with 
accept="image/*" capture="true"

Thanks for your help

**Comment by zhanziyang** [comment]
Right, `accept` has compatibility issues in different browsers.
I will add a note about this in README.
