### ISSUE TITLE
PNG files lose transparency

### ISSUE THREAD

**Issue by hawkeye64** [zhanziyang/vue-croppa#4]
I noticed that if you use vue-croppa on a PNG file with transparency, that you lose the transparency and the background is the same grey used for the background of the vue-croppa control. If the canvas color is being set to the grey color, could this become the background color for the image.

**Comment by hawkeye64** [comment]
Yes, that was exactly it. I changes the :canvas-color to 'transparent' and now existing PNGs retain their transparency. 

The downside of this is that you can no longer see the size of the canvas. 

My suggestion is to add the following properties:
:border="true"
:border-color="default"
:border-size="2"

Up to you. I can live with it the way it is now, so just a suggestion. 

All around, good work! Most other components that do the same were just way too bulky.

**Comment by zhanziyang** [comment]
Thank you for your support :))))) It's my first open source project that's actually useful for others lol.

Yes, it was intended that :canvas-color should fill the "white space" of the image. If you'd like it to be transparent and also be able to see the canvas zone, you can add some css styles on `.croppa-container`. Like this:  https://jsfiddle.net/jdcvpvty/1/

Note that the css styles won't have effects on the output image, while :canvas-color will.

**Comment by zhanziyang** [comment]
a better one: https://jsfiddle.net/jdcvpvty/2/

**Comment by hawkeye64** [comment]
Excellent! Thanks!

**Comment by Tarasovych** [comment]
@zhanziyang I faced this problem today, may I ask if setting `canvas-color="white"` is good solution for keep png transparent parts white not black?
I mean, when I left `canvas-color="transparent"` and `'image/jpeg'` at `generateBlob()`, I got black background as a result, where there is actually no background because of png format.
When I went `canvas-color="white"` and kept `'image/jpeg'` at `generateBlob()`, I got white background where it might be transparent.
My backend stores all images in jpeg anyway, so I need white where it's transparent, if png is uploaded.

**Comment by zhanziyang** [comment]
@Tarasovych Yes, you can use `canvas-color="white"` to make transparent background of  png images white

**Comment by nothingismagick** [comment]
1 1/2 years later I'd just like to say thanks for this!

**Comment by hawkeye64** [comment]
@nothingismagick :)
