### ISSUE TITLE
Chrome asking to record audio on mobile devices

### ISSUE THREAD

**Issue by luiztsmelo** [zhanziyang/vue-croppa#40]
Why is chrome asking to record audio? Is there any way to stop it?

**Comment by zhanziyang** [comment]
Weird... Are you sure it is caused by vue-croppa? Let me see have a look.

**Comment by luiztsmelo** [comment]
Yeah, I'm sure. I just added in my nuxt project and there is nothing related to audio.

**Comment by zhanziyang** [comment]
@luiztsmelo What version are you using and what is value of the `accept` prop?

**Comment by luiztsmelo** [comment]
Oh, I thought the default value of accept prop was 'image/*'. It's fine now. Thanks

**Comment by zhanziyang** [comment]
Oh yeah, the default value of accept has been removed since [v1.0.0](https://github.com/zhanziyang/vue-croppa/releases/tag/v1.0.0) because 'image/*' makes file-chooser window pops up after a small delay (on webkit browsers on PC). So I don't know what is the best default value for this attribute [shrugged].

**Comment by luiztsmelo** [comment]
Got it. Well, it's a difficult decision. One more question @zhanziyang: There is a way to put a loading feedback on croppa canvas?

**Comment by zhanziyang** [comment]
There is no built-in loading feature. But you can make your own by putting `<croppa>` and `<loading>` in the same wrapper element. And dynamically show/hide the loading with the help of some provided events (`file-choose`, `draw`).

demo: https://codepen.io/zhanziyang/pen/rGXJRy
