### ISSUE TITLE
SSR: window is not defined

### ISSUE THREAD

**Issue by Linzdigr** [zhanziyang/vue-croppa#52]
Is there a support for node env to allow server side rendering with vue-croppa?

**Comment by JohnmarkBeaty** [comment]
I am also trying to get this to work with SSR. Unfortunately I cannot get it to work with <no-ssr>
😕

**Comment by zhanziyang** [comment]
Which croppa version are you using? And can you please post the full error stack trace?

I test it in a Nuxt SSR project and it works fine. It's better if you guys can provide a demo to reproduce the problem.

**Comment by zhanziyang** [comment]
Just released a new version 1.1.4.

And in this commit (https://github.com/zhanziyang/vue-croppa/commit/ccc28f6c25ad0ea6af08f791b4b5e14f036c94c6#diff-16be38a5f3fbe3042a9ad5476f4693ec) I added
```js
if (typeof window !== 'undefined') {}
```
to make sure not to use `window` object in server-side. 

Try upgrading to this version and see if it works : ) Otherwise I need a reproducible demo, guys.

**Comment by JohnmarkBeaty** [comment]
@zhanziyang 
Chris, that was exactly what I was looking for! 
I have tested and it runs under vue ssr (I'm not using Nuxt).

Thanks!

**Comment by Linzdigr** [comment]
@zhanziyang 
It solved the problem on my side too, will make further test when I'll have some time.
Thank you!
