### ISSUE TITLE
Placeholder becomes blur when quality prop set to 1

### ISSUE THREAD

**Issue by hetsketch** [zhanziyang/vue-croppa#77]
Firstly, thanks for your component. I think it's really great. But I have some issue.
Here is a [codepen](https://codepen.io/hetsketch/pen/QmNEQV).
When I set quality prop to 1 placeholder text becomes blur. Is it possible to fix this?

**Comment by zhanziyang** [comment]
Unfortunately I don't think I can fix this as of now.
I guess you are using Mac with retina screen. If so, the blurriness is expected. Canvas or image need to be 2x larger on retina screen to look clear. That's why I use quality 2 as default value. And it's recommended to set quality >= 2.

I will think through it though.

**Comment by hetsketch** [comment]
Thank you for fast answer. Yeah i'am on Mac. So my problem is that I want to get image with same dimensions as the croppa width and height props. For example: croppa width is 300px and height is 300px too and when I call `generateDataUrl` it returns image 300x300. How to do it?

**Comment by zhanziyang** [comment]
@hetsketch  I see. Setting quality to 1 is the only way to achieve that for now and it will look blurry on Apple devices but normal on other screens.

**Comment by hetsketch** [comment]
@zhanziyang ok. I get it. You can close the issue.
