### ISSUE TITLE
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by alex-oleksenko** [zhanziyang/vue-croppa#85]
I am using `vue-croppa` component in modal dialog and experience this issue after closing my dialog during window resize.

I have investigated the issue and figured out that `auto-sizing = true`  is the property what affects on that.  The problem is with `resize` event listener in `_setSize` function.

I would suggest to use `mounted` method to add event listener and `beforeDestroy` method to remove event listener as well.

**Comment by zhanziyang** [comment]
It seems the new feature `auto-sizing` has caused a lot of problems : (((((  #83 also.
I will look into it and do the fix asap, probably in two days though, because I'm a little busy at my job lately. If it's urgent I suggest you can handle the dynamic resizing in the old way, which is to dynamically change the value for `:width` and `:height` prop.

**Comment by zhanziyang** [comment]
This is what changed:
https://github.com/zhanziyang/vue-croppa/blob/29ad64a3ed82e91e52bf6a3533d49789147a559a/src/cropper.vue#L502-L512

This method is called in `mounted`
https://github.com/zhanziyang/vue-croppa/blob/29ad64a3ed82e91e52bf6a3533d49789147a559a/src/cropper.vue#L193

I can't reproduce the error. It would be great if you have time to fix it and submit a pull request.

**Comment by zhanziyang** [comment]
Would you give v1.3.3 a try?
